apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${CLAIM_NAME}
  namespace: '${NAMESPACE@microservice-config}'
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
